// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	AppId       string `json:"appId"`
	Name        string `json:"name"`
	AdminSecret string `json:"adminSecret"`
}

type RegisterResponse struct {
	Code      int64  `json:"code" default:"0"`
	AppId     string `json:"appId"`
	AppSecret string `json:"appSecret"`
}

type LoginRequest struct {
	AppId     string `json:"appId"`
	AppSecret string `json:"appSecret"`
}

type LoginResponse struct {
	Code      int64  `json:"code" default:"0"`
	Token     string `json:"token"`
	ExpiredAt string `json:"expiredAt"`
}

type ShortenRequest struct {
	Long string `json:"long"`
}

type ShortenResponse struct {
	Code  int64  `json:"code" default:"0"`
	Short string `json:"short"`
}

type JumpRequest struct {
	Short string `path:"short"`
}
